### ISSUE TITLE
Using smtp server with authentication always throws "wrong host name" error.

### ISSUE THREAD

**Issue by doubleaxe** [hasnat/docker-events-notifier#2]
As stated in title: if you try to use smtp server with authentication - email is not sent and logs always show error "wrong host name".

This is due to fact, that smtp.PlainAuth expects host name without port, and smtp.SendMail needs port.

Will attach PR.

**Comment by doubleaxe** [comment]
https://github.com/hasnat/docker-events-notifier/pull/3

**Comment by hasnat** [comment]
closing, fixed by #3 from @doubleaxe (part of latest/0.0.2)
