### ISSUE TITLE
Add discord webhook support

### ISSUE THREAD

**Issue by strausmann** [hasnat/docker-events-notifier#5]
Can you add Discord Webhook Support ?

**Comment by hasnat** [comment]
hmm, looks like go code here is using `PostForm` (application/x-www-form-urlencoded)
need code update to add postDataEncoding or similar for discords application/json

doable.

**Comment by hasnat** [comment]
@strausmann try discord template from #6 called it `hasnat/docker-events-notifier:0.0.3.rc.1` on docker hub

**Comment by strausmann** [comment]
hey, thanks for the quick expansion. I'll try to test it tomorrow evening. no later than Monday.
